var name="pavan";
document.write(name+"<br>");
document.write(name.length+"<br>");
var firstName = "Pavan";
var secondName = "kumar";
document.write(firstName+secondName+"<br>");
document.write(firstName-secondName+"<br>");
var name1=  new String("pavan");
document.write((name==name1)+"<br>");
document.write((name===name1)+"<br>");
var name2= new String("pavan");
document.write((name1==name2)+"<br>");
document.write((name1===name2)+"<br>");
var address = 'Chitradurga is my native';
document.write(address.indexOf("is")+"<br>");
document.write(address.lastIndexOf("is")+"<br>");
document.write(address.lastIndexOf("king")+"<br>");
var find= address.search("my");
document.write(find+"<br>");
var newString ="The method takes 2 parameters the starting index position and the ending index position.";
document.write(newString+"<br>");
var res = newString.slice(10,25);
document.write(res+"<br>");
var res2 = newString.slice(-40, -20);
document.write(res2+"<br>");
var res3 = newString.slice(50);
document.write(res3+"<br>");
document.write(newString+"<br>");
var sub = newString.substring(10,30);
document.write(sub+"<br>");
document.write(newString+"<br>");
var subt = newString.substr(11,11);
document.write(subt+" and the length is "+subt.length+"<br>");
var key = newString.replace("and", "AND");
document.write(key+"<br>");
var con="I'm a software developer";
document.write(con.toUpperCase()+"<br>");
document.write(con.toLowerCase()+"<br>");
var str1="Beng";
var str2="aluru";
document.write(str1.concat(str2)+"<br>");
document.write(str1.concat("(Bendak)",str2)+"<br>");
var erase = "     trim   ";
document.write(erase+" and  the length is"+erase.length+"<br>");
document.write(erase.trim()+"and the length is "+erase.trim().length+"<br>");
document.write(newString.charAt(53)+"<br>");
document.write(newString.charCodeAt(53)+"<br>");
var spl = newString.split(" ");
document.write(spl+"<br>");